edit readme
BloomTech-Labs/coder-heroes-be-a pull request #7
Opened 2022-11-07 23:15 UTC by ashtilawat23

## Description

### This is a work in progress for BL-955.

2022-11-11 19:04 UTC, deepalisethia requested changes
Looks good to me - I would just check the indentations.

2022-11-11 19:04 UTC, deepalisethia commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
Check indentation on line 23 so that it matches with the rest

2022-11-11 20:43 UTC, razborovdb approved these changes, later dismissed
Looks good

2022-11-11 21:37 UTC, razborovdb submitted a review, later dismissed

2022-11-15 02:13 UTC, razborovdb approved these changes

2022-11-15 02:43 UTC, deepalisethia approved these changes
Looks good to me. I don't see anything that stands out after the previous changes were implemented.

2022-11-15 03:00 UTC, enbytedev commented
I assume there are plans to use `EnableWebSecurity.java`, but I'd double check that it isn't bloat from a scrapped implementation. Other than that, it looks good to me.

2022-11-15 03:02 UTC, enbytedev approved these changes
It looks good, great job!

2022-11-15 21:23 UTC, danielclark00 approved these changes
Everything looks good

2022-11-15 21:25 UTC, merged